[package]
name = "controller"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true
gilrs = "0.10"
hidapi = "2.6"

[features]
default = []
simulator = []
